// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrtt8WxUR-g5r4Kaa2RMa89Ketf-uo-L0',
    appId: '1:375945958868:web:1ba88fedb1e87fb972f241',
    messagingSenderId: '375945958868',
    projectId: 'amovtp2023grupo30',
    authDomain: 'amovtp2023grupo30.firebaseapp.com',
    storageBucket: 'amovtp2023grupo30.appspot.com',
    measurementId: 'G-P0DEX9FBHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTkOx2lthniwwn9Bt-_PnIpd_FK-qxmW4',
    appId: '1:375945958868:android:bf9bec8cd6372d4c72f241',
    messagingSenderId: '375945958868',
    projectId: 'amovtp2023grupo30',
    storageBucket: 'amovtp2023grupo30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZrTuJWLWVci13TICC_3_xl6jg0-8_Atk',
    appId: '1:375945958868:ios:690ff4e77f04b74172f241',
    messagingSenderId: '375945958868',
    projectId: 'amovtp2023grupo30',
    storageBucket: 'amovtp2023grupo30.appspot.com',
    androidClientId: '375945958868-labp1gl0btu0p8iibspkvdtn50j51ies.apps.googleusercontent.com',
    iosClientId: '375945958868-7qq1f281dat94dn597rp5injj9lth7dm.apps.googleusercontent.com',
    iosBundleId: 'com.example.tpflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZrTuJWLWVci13TICC_3_xl6jg0-8_Atk',
    appId: '1:375945958868:ios:f46b634f213c104c72f241',
    messagingSenderId: '375945958868',
    projectId: 'amovtp2023grupo30',
    storageBucket: 'amovtp2023grupo30.appspot.com',
    androidClientId: '375945958868-labp1gl0btu0p8iibspkvdtn50j51ies.apps.googleusercontent.com',
    iosClientId: '375945958868-ioe1or2ok1q1aoovlp0p2p4s2g37i6ah.apps.googleusercontent.com',
    iosBundleId: 'com.example.tpflutter.RunnerTests',
  );
}
